'use strict';
/**
 * Tray icon, generated by tools/make-tray-icon.js — do not hand-edit.
 *
 * Embedded as base64 rather than shipped as a binary asset so a clean checkout
 * always has it: the previous build referenced generated images that were
 * never committed and could not be packaged without running a generator first.
 *
 * Black plus alpha, so macOS can treat it as a template image and recolour it
 * for light, dark and highlighted menu bars.
 */

/** @type {Record<string, string>} size in points -> base64 PNG */
const TRAY_ICON_PNG = {
  "16": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAQAAAC1+jfqAAAAiUlEQVR42o1RCQ0AIQybBKQgASmTgBMkIAEJJwkJXCG8Ay7XJQTWZt0G0QqNuMBQoFQj4CXgkI44GeFwSzgF7Un1t6JnlphCz2BksqQaBZRUgmZkIpiCUUyRLXbcjctgLUGg0yTPlfRJYFeBtLC9n2qxN9nEvcl9zAw/xjwtyp92+bHqH591/e4XFvpKZPsL3McAAAAASUVORK5CYII=",
  "32": "iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAQAAADZc7J/AAAA8klEQVR42rVVbRWFIAxdBCMYgQhEMIJRaLIoRDCCUd6TA/IYDAY+3M7xB9vFfdwNgBdlAR10GYUqQDjhk+h5nahesCXQVK18iSGA44LY65uemVbOGN0QNmLbiK1SE4yBrqx9jclhK3hsJLjXE1FDcKdZOW0IXobvnO/9/7UD7mpRxIBC+Cmc9fes21haqQLumurZGfvvHUpwSqGd2PxZ4IMOrMulDr9tOr3AVhrLNi10Yu4FrRRqNt1XxIMZYlJEqY2lZG2UicTPLY5QmY41U1h5mATfnnGma0c9WSg/uHlhpU1Yqn+v9SkPy4SnbcrjOiBfCjgn2KLK8EIAAAAASUVORK5CYII="
};

module.exports = { TRAY_ICON_PNG };
